<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="autonomous_rover">

  <!-- 
    6-Wheel Autonomous Rover URDF Model
    Author: Sharan G S
    
    Hardware:
    - Jetson AGX 64GB (onboard computer)
    - RPLidar A1/A2 (360-degree laser scanner)
    - ZED 2i Stereo Camera (RGB, depth, IMU)
    - Multiple Sony lens cameras (multi-angle perception)
    - EMLID REACH M2 GPS (RTK positioning)
    - ESP32 microcontrollers (motor control, sensors)
    - 6-wheel differential drive system
  -->

  <!-- Properties -->
  <xacro:property name="chassis_length" value="0.8"/>
  <xacro:property name="chassis_width" value="0.5"/>
  <xacro:property name="chassis_height" value="0.2"/>
  <xacro:property name="chassis_mass" value="30.0"/>  <!-- Increased for Jetson AGX + batteries -->
  
  <xacro:property name="wheel_radius" value="0.125"/>
  <xacro:property name="wheel_width" value="0.08"/>
  <xacro:property name="wheel_mass" value="2.5"/>
  <xacro:property name="wheel_separation_width" value="0.55"/>
  <xacro:property name="wheel_separation_length" value="0.5"/>

  <!-- Materials -->
  <material name="black">
    <color rgba="0.1 0.1 0.1 1"/>
  </material>
  
  <material name="gray">
    <color rgba="0.5 0.5 0.5 1"/>
  </material>
  
  <material name="red">
    <color rgba="0.8 0.0 0.0 1"/>
  </material>

  <!-- Base Link -->
  <link name="base_link"/>

  <!-- Base Footprint -->
  <link name="base_footprint"/>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- Chassis -->
  <link name="chassis">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${chassis_mass}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="${(1/12) * chassis_mass * (chassis_width*chassis_width + chassis_height*chassis_height)}" 
               ixy="0.0" 
               ixz="0.0" 
               iyy="${(1/12) * chassis_mass * (chassis_length*chassis_length + chassis_height*chassis_height)}" 
               iyz="0.0" 
               izz="${(1/12) * chassis_mass * (chassis_length*chassis_length + chassis_width*chassis_width)}"/>
    </inertial>
  </link>

  <joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
    <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- Wheel Macro -->
  <xacro:macro name="wheel" params="prefix side_prefix x_pos y_pos">
    <link name="${prefix}_${side_prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${wheel_mass}"/>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" 
                 ixy="0.0" 
                 ixz="0.0" 
                 iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" 
                 iyz="0.0" 
                 izz="${(1/2) * wheel_mass * wheel_radius * wheel_radius}"/>
      </inertial>
    </link>

    <joint name="${prefix}_${side_prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_${side_prefix}_wheel"/>
      <origin xyz="${x_pos} ${y_pos} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Front Wheels -->
  <xacro:wheel prefix="front" side_prefix="left" x_pos="${wheel_separation_length/2}" y_pos="${wheel_separation_width/2}"/>
  <xacro:wheel prefix="front" side_prefix="right" x_pos="${wheel_separation_length/2}" y_pos="${-wheel_separation_width/2}"/>

  <!-- Middle Wheels -->
  <xacro:wheel prefix="middle" side_prefix="left" x_pos="0" y_pos="${wheel_separation_width/2}"/>
  <xacro:wheel prefix="middle" side_prefix="right" x_pos="0" y_pos="${-wheel_separation_width/2}"/>

  <!-- Rear Wheels -->
  <xacro:wheel prefix="rear" side_prefix="left" x_pos="${-wheel_separation_length/2}" y_pos="${wheel_separation_width/2}"/>
  <xacro:wheel prefix="rear" side_prefix="right" x_pos="${-wheel_separation_length/2}" y_pos="${-wheel_separation_width/2}"/>

  <!-- RPLidar -->
  <link name="laser">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.04" length="0.04"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.04" length="0.04"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="laser_joint" type="fixed">
    <parent link="chassis"/>
    <child link="laser"/>
    <origin xyz="0 0 ${chassis_height/2 + 0.05}" rpy="0 0 0"/>
  </joint>

  <!-- ZED 2i Camera -->
  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.033 0.175 0.03"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.033 0.175 0.03"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.15"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="chassis"/>
    <child link="camera_link"/>
    <origin xyz="${chassis_length/2 + 0.02} 0 ${chassis_height/4}" rpy="0 0 0"/>
  </joint>

  <!-- Camera Optical Frame -->
  <link name="camera_optical_frame"/>

  <joint name="camera_optical_joint" type="fixed">
    <parent link="camera_link"/>
    <child link="camera_optical_frame"/>
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
  </joint>

  <!-- IMU (from ZED 2i) -->
  <link name="imu_link"/>

  <joint name="imu_joint" type="fixed">
    <parent link="camera_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- GPS (EMLID REACH M2) -->
  <link name="gps_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.06 0.06 0.02"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.06 0.06 0.02"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001"/>
    </inertial>
  </link>

  <joint name="gps_joint" type="fixed">
    <parent link="chassis"/>
    <child link="gps_link"/>
    <origin xyz="${-chassis_length/4} 0 ${chassis_height/2 + 0.02}" rpy="0 0 0"/>
  </joint>

  <!-- Sony Camera Macro for multiple angles -->
  <xacro:macro name="sony_camera" params="name x y z roll pitch yaw">
    <link name="${name}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.025 0.025 0.025"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.025 0.025 0.025"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.05"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001"/>
      </inertial>
    </link>

    <joint name="${name}_joint" type="fixed">
      <parent link="chassis"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} ${z}" rpy="${roll} ${pitch} ${yaw}"/>
    </joint>
  </xacro:macro>

  <!-- Sony Cameras at different angles -->
  <!-- Front-left camera -->
  <xacro:sony_camera name="sony_camera_fl" 
                     x="${chassis_length/2}" 
                     y="${chassis_width/4}" 
                     z="${chassis_height/2}" 
                     roll="0" pitch="0" yaw="${pi/6}"/>
  
  <!-- Front-right camera -->
  <xacro:sony_camera name="sony_camera_fr" 
                     x="${chassis_length/2}" 
                     y="${-chassis_width/4}" 
                     z="${chassis_height/2}" 
                     roll="0" pitch="0" yaw="${-pi/6}"/>
  
  <!-- Rear camera -->
  <xacro:sony_camera name="sony_camera_rear" 
                     x="${-chassis_length/2}" 
                     y="0" 
                     z="${chassis_height/2}" 
                     roll="0" pitch="0" yaw="${pi}"/>
  
  <!-- Left side camera -->
  <xacro:sony_camera name="sony_camera_left" 
                     x="0" 
                     y="${chassis_width/2}" 
                     z="${chassis_height/2}" 
                     roll="0" pitch="0" yaw="${pi/2}"/>
  
  <!-- Right side camera -->
  <xacro:sony_camera name="sony_camera_right" 
                     x="0" 
                     y="${-chassis_width/2}" 
                     z="${chassis_height/2}" 
                     roll="0" pitch="0" yaw="${-pi/2}"/>

</robot>
